---
- stat:
    path: "{{ php_dir }}/{{ version }}"
  register: specific_version_php

- lineinfile:
    path: "{{ phpbuild_root }}/share/php-build/definitions/{{ version }}"
    line: 'configure_option "--with-libzip"'
  when: version is match("^7")

- lineinfile:
    path: "{{ phpbuild_root }}/share/php-build/definitions/{{ version }}"
    line: 'configure_option "--with-mcrypt=/usr"'
  when: version is match("^5")

- shell: "{{ phpbuild_root }}/bin/php-build {{ version }} {{ php_dir }}/{{ version }}"
  when: not specific_version_php.stat.exists

- lineinfile:
    path: "{{ php_dir }}/{{ version }}/etc/php.ini"
    regexp: '.*ate.timezone.*'
    line: "date.timezone={{ timezone }}"
